### ISSUE TITLE
Error when try to add the plugin to a phonegap build - File not found

### ISSUE THREAD

**Issue by mzsolti** [developingwild/cordova-plugin-bartinter#2]
Installing "cordova-plugin-bartinter@0.1.0-alpha" for android
Failed to install 'cordova-plugin-bartinter':Error: ENOENT: no such file or directory, open '/project/cordova/plugins/cordova-plugin-bartinter/www/BarTinter.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/prepare.js:119:36
    at Array.forEach (native)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/prepare.js:99:19
    at Array.forEach (native)
    at Object.handlePrepare (/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/prepare.js:78:24)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:587:28
    at _fulfilled (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
ENOENT: no such file or directory, open '/project/cordova/plugins/cordova-plugin-bartinter/www/BarTinter.js'

Probably just the filename need to be changed from www/bartinter.js to www/BarTinter.js

**Comment by ApocalypsjeNL** [comment]
Fixed.
